export const arrayProductos = [
    {
        "id": 0,
        "name": "Samsung Np300e5a", 
        "categoria": "Notebooks", 
        "description": "Samsung moderna de 8gb de RAM con un procesador Intel i5 de 10ma Gen",
        "price": 25000, 
        "stock": 10,
        "pictureUrl": "https://images.icecat.biz/img/norm/high/14806339-6225.jpg",
        "cantidadComprada": 0,
    },
    {
        "id": 1,
        "name": "Silla Gamer Ragnar", 
        "categoria": "Sillas gamer", 
        "description": "Silla Gamer Ergonómica Con Cojines Lumbar Premium Ragnar",
        "price": 5000, 
        "stock": 4,
        "pictureUrl": "https://http2.mlstatic.com/D_NQ_NP_706674-MLA47035112498_082021-O.webp",
        "cantidadComprada": 0,
    },
    {
        "id": 2,
        "name": "Auriculares Redragon Zeus 2", 
        "categoria": "Perifericos", 
        "description": "7.1 Virtual via USB, stereo por ficha 3.5",
        "price": 980, 
        "stock": 7, 
        "pictureUrl": "https://s3-sa-east-1.amazonaws.com/saasargentina/4n7ZqbpPKpfaIJ7A55kv/imagen",
        "cantidadComprada": 0,
    },
    {
        "id": 3,
        "name": "HP 240 g7", 
        "categoria": "Notebooks", 
        "description": "Hp moderna de 16 de RAM con un procesador Intel i9 de 10ma Gen",
        "price": 35000, 
        "stock": 15,
        "pictureUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPw-wzSosoAL6Iv_nyo1eBcvhXopXIcckdUwz4accUjVIZ4VPdvj9u4yBHTBSGPgdRA-6LH7nt&usqp=CAc",
        "cantidadComprada": 0,
    }
]